module.exports = {
  testEnvironment: "node",
  roots: [
    "<rootDir>/test",
    "<rootDir>/e2e",
    // "<rootDir>/lambda",
    // "<rootDir>/lib",
    // "<rootDir>/bin",
  ],
  testMatch: ["**/*.test.ts","**/*.e2e.ts"],
  transform: {
    "^.+\\.tsx?$": "ts-jest",
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverage: true,
  collectCoverageFrom: [
    // "<rootDir>/lambda/api/*.ts",
    "**.{ts,tsx}",
    "*.{ts,tsx}",
    "**/*.{ts,tsx}",
    "**/**/*.{ts,tsx}",
    "!**/script/**",
    "!**/node_modules/**",
    "!**/my_modules/**",
    "!**/test/**",
    "!**/**/*.d.ts",
  ],
  // coverageReporters: ["text"],
  coverageReporters: ["text", "json", "html","lcov", "json-summary",],
};
