name: develop-deploy

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Confirm git status
        run: git status

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Installs dependencies
        run: npm ci

      - name: Run unittest
        run: npm run test:unit

      - name: Run cdk diff check
        run: npm run cdk:synth target=dev
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run cdk deploy
        run: npm run cdk:deploy target=dev
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
